services:
  localstack:
    container_name: infra-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=cloudwatch,logs,sqs
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./init-scripts.sh:/etc/localstack/init/ready.d/init-scripts.sh
    networks:
      microservices-network:
        aliases:
          - localstack
    healthcheck:
      test: ["CMD", "awslocal", "cloudwatch", "describe-alarms"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  microservices-network:
    external: true
    name: examenprimerparcial_microservices-network
